// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addItem.ts";
import * as $$$$$$$$$1 from "./actions/createInvitee.ts";
import * as $$$$$$$$$2 from "./actions/removeInvitee.ts";
import * as $$$$$$$$$3 from "./actions/removeItem.ts";
import * as $$$$$$$$$4 from "./actions/reserveItem.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$0 from "./loaders/authenticatedUser.ts";
import * as $$$1 from "./loaders/invitee.ts";
import * as $$$2 from "./loaders/invitees.ts";
import * as $$$3 from "./loaders/item.ts";
import * as $$$4 from "./loaders/itemList.ts";
import * as $$$5 from "./loaders/userCookie.ts";
import * as $$$6 from "./loaders/vtexProductSearch.ts";
import * as $$$$$$0 from "./sections/FeaturedProducts.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Header.tsx";
import * as $$$$$$3 from "./sections/Invitations.tsx";
import * as $$$$$$5 from "./sections/ItemsList.tsx";
import * as $$$$$$4 from "./sections/ItWorks.tsx";
import * as $$$$$$6 from "./sections/Login.tsx";
import * as $$$$$$7 from "./sections/MyList.tsx";
import * as $$$$$$8 from "./sections/Theme/Theme.tsx";
import * as $$$$$$9 from "./sections/TitleList.tsx";
import * as $$$$$$10 from "./sections/UrlList.tsx";

const manifest = {
  "loaders": {
    "site/loaders/authenticatedUser.ts": $$$0,
    "site/loaders/invitee.ts": $$$1,
    "site/loaders/invitees.ts": $$$2,
    "site/loaders/item.ts": $$$3,
    "site/loaders/itemList.ts": $$$4,
    "site/loaders/userCookie.ts": $$$5,
    "site/loaders/vtexProductSearch.ts": $$$6,
  },
  "sections": {
    "site/sections/FeaturedProducts.tsx": $$$$$$0,
    "site/sections/Footer.tsx": $$$$$$1,
    "site/sections/Header.tsx": $$$$$$2,
    "site/sections/Invitations.tsx": $$$$$$3,
    "site/sections/ItemsList.tsx": $$$$$$5,
    "site/sections/ItWorks.tsx": $$$$$$4,
    "site/sections/Login.tsx": $$$$$$6,
    "site/sections/MyList.tsx": $$$$$$7,
    "site/sections/Theme/Theme.tsx": $$$$$$8,
    "site/sections/TitleList.tsx": $$$$$$9,
    "site/sections/UrlList.tsx": $$$$$$10,
  },
  "actions": {
    "site/actions/addItem.ts": $$$$$$$$$0,
    "site/actions/createInvitee.ts": $$$$$$$$$1,
    "site/actions/removeInvitee.ts": $$$$$$$$$2,
    "site/actions/removeItem.ts": $$$$$$$$$3,
    "site/actions/reserveItem.ts": $$$$$$$$$4,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
