// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addItem.ts";
import * as $$$$$$$$$1 from "./actions/reserveItem.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/vtex.ts";
import * as $$$$$$$$$$$2 from "./apps/site.ts";
import * as $$$0 from "./loaders/item.ts";
import * as $$$1 from "./loaders/itemList.ts";
import * as $$$2 from "./loaders/vtexProductSearch.ts";
import * as $$$$$$0 from "./sections/FeaturedProducts.tsx";
import * as $$$$$$1 from "./sections/Footer.tsx";
import * as $$$$$$2 from "./sections/Header.tsx";
import * as $$$$$$4 from "./sections/ItemsList.tsx";
import * as $$$$$$3 from "./sections/ItWorks.tsx";
import * as $$$$$$5 from "./sections/Login.tsx";
import * as $$$$$$6 from "./sections/MyList.tsx";
import * as $$$$$$7 from "./sections/Theme/Theme.tsx";
import * as $$$$$$8 from "./sections/TitleList.tsx";
import * as $$$$$$9 from "./sections/UrlList.tsx";

const manifest = {
  "loaders": {
    "site/loaders/item.ts": $$$0,
    "site/loaders/itemList.ts": $$$1,
    "site/loaders/vtexProductSearch.ts": $$$2,
  },
  "sections": {
    "site/sections/FeaturedProducts.tsx": $$$$$$0,
    "site/sections/Footer.tsx": $$$$$$1,
    "site/sections/Header.tsx": $$$$$$2,
    "site/sections/ItemsList.tsx": $$$$$$4,
    "site/sections/ItWorks.tsx": $$$$$$3,
    "site/sections/Login.tsx": $$$$$$5,
    "site/sections/MyList.tsx": $$$$$$6,
    "site/sections/Theme/Theme.tsx": $$$$$$7,
    "site/sections/TitleList.tsx": $$$$$$8,
    "site/sections/UrlList.tsx": $$$$$$9,
  },
  "actions": {
    "site/actions/addItem.ts": $$$$$$$$$0,
    "site/actions/reserveItem.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/htmx.ts": $$$$$$$$$$$0,
    "site/apps/deco/vtex.ts": $$$$$$$$$$$1,
    "site/apps/site.ts": $$$$$$$$$$$2,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
